= Step 7: Add Pet Owner

==== *the basics* in 10 minutes

'''
*Checkout the code with the results of this exercise on:*

* link:https://github.com/johandoornenbal/petclinic_mynewcode/tree/tutorial04[]

'''
The tasks we will perform are:

* Add the `Owner` entity and corresponding `Owners` domain service (repository).
* Add a query to find `Owner` s by name.

First try setting up `Owner` with the properties `firstName` and `lastName yourself`.

Then set up `Owners` domain service with method `addOwner()`.

Compare your code to ours. You may have wondered already how to define the relationship between an
`Owner` and it's `Pet` s. Here's is how we implement this 2-way relationship:

on `Pet` we define `owner` of type `Owner` since a `Pet` can have 0 or 1 `Owner` - note how `owner` is annotated
with `@Column(allowsNull = "true")`:

----
private Owner owner;

@MemberOrder(sequence = "3")
@Column(name = "ownerId", allowsNull = "true")
public Owner getOwner() {
    return owner;
}

public void setOwner(final Owner owner) {
    this.owner = owner;
}
----

on `Owner` we define a collection `pets` since an `Owner` can own 0 or more `Pet` s:

----
@Persistent(mappedBy = "owner", dependentElement = "false")
private SortedSet<Pet> pets = new TreeSet<Pet>();

@MemberOrder(sequence = "3")
public SortedSet<Pet> getPets() {
    return pets;
}

public void setPets(final SortedSet<Pet> pets) {
    this.pets = pets;
}
----

Note the annotation `@Persistent(mappedBy = "owner", dependentElement = "false")` property `owner` on `Pet` is indicated to define the relationship.





'''
link:7_petclinic_petspecies.adoc[<< BACK] | link:9_petclinic_.adoc[NEXT >>]