= Step 7: Add Pet Owner

==== *the basics* in 10 minutes

'''
*Checkout the code with the results of this exercise on:*

* link:https://github.com/johandoornenbal/petclinic_mynewcode/tree/tutorial04[]

'''
The tasks we will perform are:

* Add the `PetOwner` entity and corresponding `PetOwners` domain service (repository).
* Add a query to find `PetOwner` s by name.

First try setting up `PetOwner` with the properties `firstName` and `lastName yourself`.

Then set up `PetOwners` domain service with method `addOwner()`.

Compare your code to ours. You may have wondered already how to define the relationship between an
`PetOwner` and it's `Pet` s. Here's is how we implement this 2-way relationship:

on `Pet` we define `petOwner` of type `PetOwner` since a `Pet` can have 0 or 1 `PetOwner` - note how `petOwner` is annotated
with `@Column(allowsNull = "true")`:

----
private PetOwner petOwner;

    @MemberOrder(sequence = "3")
    @Column(name = "ownerId", allowsNull = "true")
    public PetOwner getPetOwner() {
        return petOwner;
    }

    public void setPetOwner(final PetOwner petOwner) {
        this.petOwner = petOwner;
    }
----

on `PetOwner` we define a collection `pets` since an `PetOwner` can own 0 or more `Pet` s:

----
@Persistent(mappedBy = "petOwner", dependentElement = "false")
    private SortedSet<Pet> pets = new TreeSet<Pet>();

    @MemberOrder(sequence = "3")
    @CollectionLayout(render = RenderType.EAGERLY)
    public SortedSet<Pet> getPets() {
        return pets;
    }

    public void setPets(final SortedSet<Pet> pets) {
        this.pets = pets;
    }
----

Note the annotation `@Persistent(mappedBy = "petOwner", dependentElement = "false")` property `petOwner` on `Pet` is indicated to define the relationship.





'''
link:7_petclinic_petspecies.adoc[<< BACK] | link:9_petclinic_.adoc[NEXT >>]